// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const FROM_THE_LODGE_SONG: SongManifest = {
  id: "subterranean_from-the-lodge",
  slug: "from-the-lodge",
  title: "From The Lodge",
  artistId: "subterranean",
  albumId: "subterranean_gracie-s-oasis",
  trackNumber: 7,
  difficulty: 5,
  energy: 3,
  moodTags: [
    "melodic",
    "uplifting",
    "deep house",
    "ambient house",
    "microhouse"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'violet',
  },
  loadConfig: async () => (await import("./config")).SONG7_CONFIG,
};
