// Generated by scripts/scaffold_content.py
import { MANIFESTATION_SONG } from "./manifestation/song";
import { TWENTY_TITLES_SONG } from "./twenty-titles/song";
import { MORE_MONEY_SONG } from "./more-money/song";
import { LESS_WEALTH_SONG } from "./less-wealth/song";
import { TRAINED_TO_COMMIT_SONG } from "./trained-to-commit/song";
import { HEALTHBELT_5_SONG } from "./healthbelt-5/song";
import { HYPNO_S_HEADPHONES_SONG } from "./hypno-s-headphones/song";
import { MANATEE_SONG } from "./manatee/song";
import { A_BRIDGE_WITH_NO_HOLE_SONG } from "./a-bridge-with-no-hole/song";
import { OVER_THE_CLIFF_SONG } from "./over-the-cliff/song";
import type { SongManifest } from "../../../schema";

export const CHEMIKAL_FOODS_LTD_MANIFESTATION_SONGS: SongManifest[] = [
  MANIFESTATION_SONG,
  TWENTY_TITLES_SONG,
  MORE_MONEY_SONG,
  LESS_WEALTH_SONG,
  TRAINED_TO_COMMIT_SONG,
  HEALTHBELT_5_SONG,
  HYPNO_S_HEADPHONES_SONG,
  MANATEE_SONG,
  A_BRIDGE_WITH_NO_HOLE_SONG,
  OVER_THE_CLIFF_SONG,
];
