// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const WRIST_AND_PALM_SONG: SongManifest = {
  id: "subterranean_wrist-and-palm",
  slug: "wrist-and-palm",
  title: "Wrist And Palm",
  artistId: "subterranean",
  albumId: "subterranean_gracie-s-oasis",
  trackNumber: 9,
  difficulty: 5,
  energy: 3,
  moodTags: [
    "melodic",
    "uplifting",
    "deep house",
    "ambient house",
    "microhouse"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'gold',
  },
  loadConfig: async () => (await import("./config")).SONG9_CONFIG,
};
