// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const GOT_IT_LOCKED_SONG: SongManifest = {
  id: "subterranean_got-it-locked",
  slug: "got-it-locked",
  title: "Got It Locked",
  artistId: "subterranean",
  albumId: "subterranean_gracie-s-oasis",
  trackNumber: 3,
  difficulty: 5,
  energy: 3,
  moodTags: [
    "melodic",
    "uplifting",
    "deep house",
    "ambient house",
    "microhouse"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'violet',
  },
  loadConfig: async () => (await import("./config")).SONG3_CONFIG,
};
