// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const LOST_IT_ON_SCHAEFER_SONG: SongManifest = {
  id: "subterranean_lost-it-on-schaefer",
  slug: "lost-it-on-schaefer",
  title: "Lost It On Schaefer",
  artistId: "subterranean",
  albumId: "subterranean_gracie-s-oasis",
  trackNumber: 1,
  difficulty: 5,
  energy: 3,
  moodTags: [
    "melodic",
    "uplifting",
    "deep house",
    "ambient house",
    "microhouse"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'gold',
  },
  loadConfig: async () => (await import("./config")).SONG1_CONFIG,
};
