// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";
import { SONG3_CONFIG } from "./config";

export const BROKEN_CASTLE_SONG: SongManifest = {
  id: "subterranean_broken-castle",
  slug: "broken-castle",
  title: "Broken Castle",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 3,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "hidden",
  config: SONG3_CONFIG,
};
