// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const BROKEN_CASTLE_SONG: SongManifest = {
  id: "subterranean_broken-castle",
  slug: "broken-castle",
  title: "Broken Castle",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 3,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'ultraviolet',
  },
  loadConfig: async () => (await import("./config")).SONG3_CONFIG,
};
