// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const ROSEBLOOM_SONG: SongManifest = {
  id: "subterranean_rosebloom",
  slug: "rosebloom",
  title: "Rosebloom",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 15,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG15_CONFIG,
};
