// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const TWENTY_TITLES_SONG: SongManifest = {
  id: "chemikal-foods-ltd_twenty-titles",
  slug: "twenty-titles",
  title: "Twenty Titles",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 2,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG2_CONFIG,
};
