// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const OVER_THE_CLIFF_SONG: SongManifest = {
  id: "chemikal-foods-ltd_over-the-cliff",
  slug: "over-the-cliff",
  title: "Over The Cliff",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 10,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG10_CONFIG,
};
