// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";
import panorama from "../../assets/cows.webp";

export const OVER_THE_CLIFF_SONG: SongManifest = {
  id: "chemikal-foods-ltd_over-the-cliff",
  slug: "over-the-cliff",
  title: "Over The Cliff",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 10,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'dream',
    yawCenterDegrees: -45,
    panoramaUrl: panorama,
    zoom: 2.0,
  },
  loadConfig: async () => (await import("./config")).SONG10_CONFIG,
};
