// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const DANGER_DRIVE_SONG: SongManifest = {
  id: "subterranean_danger-drive",
  slug: "danger-drive",
  title: "Danger Drive",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 11,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'overload',
  },
  loadConfig: async () => (await import("./config")).SONG11_CONFIG,
};
