// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const STITCHES_SONG: SongManifest = {
  id: "subterranean_stitches",
  slug: "stitches",
  title: "Stitches",
  artistId: "subterranean",
  albumId: "subterranean_gracie-s-oasis",
  trackNumber: 6,
  difficulty: 5,
  energy: 3,
  moodTags: [
    "melodic",
    "uplifting",
    "deep house",
    "ambient house",
    "microhouse"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'peach',
  },
  loadConfig: async () => (await import("./config")).SONG6_CONFIG,
};
