// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const OVER_MY_SHOULDER_SONG: SongManifest = {
  id: "subterranean_over-my-shoulder",
  slug: "over-my-shoulder",
  title: "Over My Shoulder",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 6,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'overload',
  },
  loadConfig: async () => (await import("./config")).SONG6_CONFIG,
};
