// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";
import panorama from "../../assets/subway.webp";

export const HEALTHBELT_5_SONG: SongManifest = {
  id: "chemikal-foods-ltd_healthbelt-5",
  slug: "healthbelt-5",
  title: "Healthbelt 5",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 6,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'warm',
    yawCenterDegrees: 90,
    panoramaUrl: panorama,
    zoom: 2.0,
  },
  loadConfig: async () => (await import("./config")).SONG6_CONFIG,
};
