// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const GRACIE_S_OASIS_SONG: SongManifest = {
  id: "subterranean_gracie-s-oasis",
  slug: "gracie-s-oasis",
  title: "Gracie's Oasis",
  artistId: "subterranean",
  albumId: "subterranean_gracie-s-oasis",
  trackNumber: 11,
  difficulty: 5,
  energy: 3,
  moodTags: [
    "melodic",
    "uplifting",
    "deep house",
    "ambient house",
    "microhouse"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'violet',
  },
  loadConfig: async () => (await import("./config")).SONG11_CONFIG,
};
