// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const A_GLIMPSE_OF_GREEN_SONG: SongManifest = {
  id: "sector-seven_a-glimpse-of-green",
  slug: "a-glimpse-of-green",
  title: "A Glimpse Of Green",
  artistId: "sector-seven",
  albumId: "sector-seven_artificial-heat",
  trackNumber: 7,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'cobalt'
  },
  loadConfig: async () => (await import("./config")).SONG7_CONFIG,
};
