// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const A_BRIDGE_WITH_NO_HOLE_SONG: SongManifest = {
  id: "chemikal-foods-ltd_a-bridge-with-no-hole",
  slug: "a-bridge-with-no-hole",
  title: "A Bridge With No Hole",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 9,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG9_CONFIG,
};
