// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const WITH_NO_SOUND_SONG: SongManifest = {
  id: "sector-seven_with-no-sound",
  slug: "with-no-sound",
  title: "With No Sound",
  artistId: "sector-seven",
  albumId: "sector-seven_artificial-heat",
  trackNumber: 10,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'ember'
  },
  loadConfig: async () => (await import("./config")).SONG10_CONFIG,
};
