// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const NATURALLY_SONG: SongManifest = {
  id: "sector-seven_naturally",
  slug: "naturally",
  title: "Naturally",
  artistId: "sector-seven",
  albumId: "sector-seven_artificial-heat",
  trackNumber: 2,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'teal'
  },
  loadConfig: async () => (await import("./config")).SONG2_CONFIG,
};
