// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const HALF_PAINTED_SONG: SongManifest = {
  id: "subterranean_half-painted",
  slug: "half-painted",
  title: "Half Painted",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 14,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG14_CONFIG,
};
