// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const ESCAPE_PT_1_SONG: SongManifest = {
  id: "subterranean_escape-pt-1",
  slug: "escape-pt-1",
  title: "Escape Pt.1",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 12,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG12_CONFIG,
};
