// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const CHEESEBOARD_SONG: SongManifest = {
  id: "subterranean_cheeseboard",
  slug: "cheeseboard",
  title: "Cheeseboard",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 8,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG8_CONFIG,
};
