// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";
import panorama from "../../assets/subway.webp";

export const MORE_MONEY_SONG: SongManifest = {
  id: "chemikal-foods-ltd_more-money",
  slug: "more-money",
  title: "More Money",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 3,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'dream',
    yawCenterDegrees: -60,
    panoramaUrl: panorama,
  },
  loadConfig: async () => (await import("./config")).SONG3_CONFIG,
};
