// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const DISTORTED_BY_FEAR_SONG: SongManifest = {
  id: "sector-seven_distorted-by-fear",
  slug: "distorted-by-fear",
  title: "Distorted by Fear",
  artistId: "sector-seven",
  albumId: "sector-seven_artificial-heat",
  trackNumber: 4,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'teal'
  },
  loadConfig: async () => (await import("./config")).SONG4_CONFIG,
};
