// Generated by scripts/scaffold_content.py
import { BIRMINGHAM_CENTRAL_SONG } from "./birmingham-central/song";
import { SHOVEL_SONG } from "./shovel/song";
import { BROKEN_CASTLE_SONG } from "./broken-castle/song";
import { HOT_ROOM_SONG } from "./hot-room/song";
import { ANALGESIC_SONG } from "./analgesic/song";
import { OVER_MY_SHOULDER_SONG } from "./over-my-shoulder/song";
import { JUMP_JUMPER_SONG } from "./jump-jumper/song";
import { CHEESEBOARD_SONG } from "./cheeseboard/song";
import { SPAR_CAR_PARK_SONG } from "./spar-car-park/song";
import { ROLLING_SONG } from "./rolling/song";
import { DANGER_DRIVE_SONG } from "./danger-drive/song";
import { ESCAPE_PT_1_SONG } from "./escape-pt-1/song";
import { WOODEN_SNARES_SONG } from "./wooden-snares/song";
import { HALF_PAINTED_SONG } from "./half-painted/song";
import { ROSEBLOOM_SONG } from "./rosebloom/song";
import type { SongManifest } from "../../../schema";

export const SUBTERRANEAN_ECHO_CHAMBER_SONGS: SongManifest[] = [
  BIRMINGHAM_CENTRAL_SONG,
  SHOVEL_SONG,
  BROKEN_CASTLE_SONG,
  HOT_ROOM_SONG,
  ANALGESIC_SONG,
  OVER_MY_SHOULDER_SONG,
  JUMP_JUMPER_SONG,
  CHEESEBOARD_SONG,
  SPAR_CAR_PARK_SONG,
  ROLLING_SONG,
  DANGER_DRIVE_SONG,
  ESCAPE_PT_1_SONG,
  WOODEN_SNARES_SONG,
  HALF_PAINTED_SONG,
  ROSEBLOOM_SONG,
];
