// Generated by scripts/scaffold_content.py
import { BIRMINGHAM_CENTRAL_SONG } from "./birmingham-central/song";
import type { SongManifest } from "../../../schema";

export const SUBTERRANEAN_ECHO_CHAMBER_SONGS: SongManifest[] = [
  BIRMINGHAM_CENTRAL_SONG,
];
