// Generated by scripts/scaffold_content.py
import { DRUNK_AGAIN_SONG } from "./drunk-again/song";
import { NATURALLY_SONG } from "./naturally/song";
import { I_SAW_THE_SKY_SONG } from "./i-saw-the-sky/song";
import { DISTORTED_BY_FEAR_SONG } from "./distorted-by-fear/song";
import { TWISTED_SONG } from "./twisted/song";
import { TUMBLING_DOWN_SONG } from "./tumbling-down/song";
import { A_GLIMPSE_OF_GREEN_SONG } from "./a-glimpse-of-green/song";
import { TRIANGLES_SONG } from "./triangles/song";
import { BURNING_SONG } from "./burning/song";
import { WITH_NO_SOUND_SONG } from "./with-no-sound/song";
import type { SongManifest } from "../../../schema";

export const SECTOR_SEVEN_ARTIFICIAL_HEAT_SONGS: SongManifest[] = [
  DRUNK_AGAIN_SONG,
  NATURALLY_SONG,
  I_SAW_THE_SKY_SONG,
  DISTORTED_BY_FEAR_SONG,
  TWISTED_SONG,
  TUMBLING_DOWN_SONG,
  A_GLIMPSE_OF_GREEN_SONG,
  TRIANGLES_SONG,
  BURNING_SONG,
  WITH_NO_SOUND_SONG,
];
