// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";
import subwayBg from "../../assets/subway.webp";

export const MANIFESTATION_SONG: SongManifest = {
  id: "chemikal-foods-ltd_manifestation",
  slug: "manifestation",
  title: "Manifestation",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 1,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'night',
    yawCenterDegrees: -90,
    panoramaUrl: subwayBg,
  },
  loadConfig: async () => (await import("./config")).SONG1_CONFIG,
};
