// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const MANIFESTATION_SONG: SongManifest = {
  id: "chemikal-foods-ltd_manifestation",
  slug: "manifestation",
  title: "Manifestation",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 1,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG1_CONFIG,
};
