// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const CHASING_SONG: SongManifest = {
  id: "subterranean_chasing",
  slug: "chasing",
  title: "Chasing",
  artistId: "subterranean",
  albumId: "subterranean_gracie-s-oasis",
  trackNumber: 2,
  difficulty: 5,
  energy: 3,
  moodTags: [
    "melodic",
    "uplifting",
    "deep house",
    "ambient house",
    "microhouse"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'peach',
  },
  loadConfig: async () => (await import("./config")).SONG2_CONFIG,
};
