// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";
import { SONG10_CONFIG } from "./config";

export const ROLLING_SONG: SongManifest = {
  id: "subterranean_rolling",
  slug: "rolling",
  title: "Rolling",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 10,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  config: SONG10_CONFIG,
};
