// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const ROLLING_SONG: SongManifest = {
  id: "subterranean_rolling",
  slug: "rolling",
  title: "Rolling",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 10,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'toxic-teal',
  },
  loadConfig: async () => (await import("./config")).SONG10_CONFIG,
};
