// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const THE_PLATE_SONG: SongManifest = {
  id: "subterranean_the-plate",
  slug: "the-plate",
  title: "The Plate",
  artistId: "subterranean",
  albumId: "subterranean_gracie-s-oasis",
  trackNumber: 4,
  difficulty: 5,
  energy: 3,
  moodTags: [
    "melodic",
    "uplifting",
    "deep house",
    "ambient house",
    "microhouse"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'teal-dusk',
  },
  loadConfig: async () => (await import("./config")).SONG4_CONFIG,
};
