// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const DRUNK_AGAIN_SONG: SongManifest = {
  id: "sector-seven_drunk-again",
  slug: "drunk-again",
  title: "Drunk Again",
  artistId: "sector-seven",
  albumId: "sector-seven_artificial-heat",
  trackNumber: 1,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG1_CONFIG,
};
