// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const TUMBLING_DOWN_SONG: SongManifest = {
  id: "sector-seven_tumbling-down",
  slug: "tumbling-down",
  title: "Tumbling Down",
  artistId: "sector-seven",
  albumId: "sector-seven_artificial-heat",
  trackNumber: 6,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG6_CONFIG,
};
