// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const BIRMINGHAM_CENTRAL_SONG: SongManifest = {
  id: "subterranean_birmingham-central",
  slug: "birmingham-central",
  title: "Birmingham Central",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 1,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG1_CONFIG,
};
