// Generated by scripts/scaffold_content.py
import type { ArtistManifest } from "../../schema";

export const CHEMIKAL_FOODS_LTD_ARTIST: ArtistManifest = {
  id: "chemikal-foods-ltd",
  slug: "chemikal-foods-ltd",
  name: "Chemikal Foods Ltd",
};
