// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const TWISTED_SONG: SongManifest = {
  id: "sector-seven_twisted",
  slug: "twisted",
  title: "Twisted",
  artistId: "sector-seven",
  albumId: "sector-seven_artificial-heat",
  trackNumber: 5,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG5_CONFIG,
};
