// Generated by scripts/scaffold_content.py
import type { AlbumManifest } from "../../schema";
import goCover from "./cover.webp";

export const SUBTERRANEAN_GRACIE_S_OASIS_ALBUM: AlbumManifest = {
  id: "subterranean_gracie-s-oasis",
  slug: "subterranean_gracie-s-oasis",
  title: "Gracie's Oasis",
  artistId: "subterranean",
  coverArt: goCover,
  year: 2026,
  theme: {
    accent: "#7ee9ef",
    accentSoft: "#213645",
    text: "#eaf7ff",
    background: "#081522",
    panel: "#101b29",
    backdropPreset: "ibiza-sun",
  },
  tags: [
    "melodic",
    "uplifting",
    "deep house",
    "ambient house",
    "microhouse"
],
  songIds: [
    "subterranean_lost-it-on-schaefer",
    "subterranean_chasing",
    "subterranean_got-it-locked",
    "subterranean_the-plate",
    "subterranean_northbound",
    "subterranean_stitches",
    "subterranean_from-the-lodge",
    "subterranean_the-bench",
    "subterranean_wrist-and-palm",
    "subterranean_that-unit",
    "subterranean_gracie-s-oasis",
  ],
  sortOrder: 2,
  availability: "included",
};
