import { SONG10_CONFIG } from "../game/song10";
import { SONG1_CONFIG } from "../game/song1";
import { SONG2_CONFIG } from "../game/song2";
import { SONG3_CONFIG } from "../game/song3";
import { SONG4_CONFIG } from "../game/song4";
import { SONG5_CONFIG } from "../game/song5";
import { SONG6_CONFIG } from "../game/song6";
import { SONG7_CONFIG } from "../game/song7";
import { SONG8_CONFIG } from "../game/song8";
import { SONG9_CONFIG } from "../game/song9";
import type { SongEntry } from "./types";

export const SONGS: SongEntry[] = [
  {
    id: "sector-seven_giant-reset",
    slug: "sector-seven_giant-reset",
    title: "Giant Reset",
    artistId: "sector-seven",
    albumId: "sector-seven_furnace-transmission",
    trackNumber: 1,
    difficulty: 2,
    energy: 2,
    moodTags: ["dark", "driving"],
    recommendedWeight: 0.66,
    availability: "included",
    config: SONG1_CONFIG,
  },
  {
    id: "sector-seven_fatman",
    slug: "sector-seven_fatman",
    title: "Fatman",
    artistId: "sector-seven",
    albumId: "sector-seven_furnace-transmission",
    trackNumber: 2,
    difficulty: 3,
    energy: 4,
    moodTags: ["dark", "hypnotic", "heavy"],
    recommendedWeight: 0.98,
    availability: "included",
    config: SONG2_CONFIG,
  },
  {
    id: "sector-seven_sunup",
    slug: "sector-seven_sunup",
    title: "Sunup",
    artistId: "sector-seven",
    albumId: "sector-seven_furnace-transmission",
    trackNumber: 3,
    difficulty: 3,
    energy: 3,
    moodTags: ["dark", "broken"],
    recommendedWeight: 0.74,
    availability: "included",
    config: SONG3_CONFIG,
  },
  {
    id: "sector-seven_euro-pacmenz",
    slug: "sector-seven_euro-pacmenz",
    title: "Euro Pacmenz",
    artistId: "sector-seven",
    albumId: "sector-seven_furnace-transmission",
    trackNumber: 4,
    difficulty: 2,
    energy: 3,
    moodTags: ["driving", "melodic"],
    recommendedWeight: 0.7,
    availability: "included",
    config: SONG4_CONFIG,
  },
  {
    id: "sector-seven_constant-enople",
    slug: "sector-seven_constant-enople",
    title: "Constant Enople",
    artistId: "sector-seven",
    albumId: "sector-seven_furnace-transmission",
    trackNumber: 5,
    difficulty: 3,
    energy: 4,
    moodTags: ["heavy", "driving"],
    recommendedWeight: 0.76,
    availability: "included",
    config: SONG5_CONFIG,
  },
  {
    id: "sector-seven_pablo",
    slug: "sector-seven_pablo",
    title: "Pablo",
    artistId: "sector-seven",
    albumId: "sector-seven_furnace-transmission",
    trackNumber: 6,
    difficulty: 4,
    energy: 4,
    moodTags: ["dark", "broken", "heavy"],
    recommendedWeight: 0.82,
    availability: "included",
    config: SONG6_CONFIG,
  },
  {
    id: "sector-seven_jelling-bad-words",
    slug: "sector-seven_jelling-bad-words",
    title: "Jelling Bad Words",
    artistId: "sector-seven",
    albumId: "sector-seven_furnace-transmission",
    trackNumber: 7,
    difficulty: 3,
    energy: 3,
    moodTags: ["hypnotic", "melodic"],
    recommendedWeight: 0.72,
    availability: "included",
    config: SONG7_CONFIG,
  },
  {
    id: "sector-seven_hamtrack",
    slug: "sector-seven_hamtrack",
    title: "Hamtrack",
    artistId: "sector-seven",
    albumId: "sector-seven_furnace-transmission",
    trackNumber: 8,
    difficulty: 4,
    energy: 5,
    moodTags: ["heavy", "dark", "driving"],
    recommendedWeight: 0.8,
    availability: "included",
    config: SONG8_CONFIG,
  },
  {
    id: "sector-seven_burried",
    slug: "sector-seven_burried",
    title: "Burried",
    artistId: "sector-seven",
    albumId: "sector-seven_furnace-transmission",
    trackNumber: 9,
    difficulty: 4,
    energy: 4,
    moodTags: ["ambient", "broken", "dark"],
    recommendedWeight: 0.78,
    availability: "included",
    config: SONG9_CONFIG,
  },
  {
    id: "sector-seven_running-its-course",
    slug: "sector-seven_running-its-course",
    title: "Running Its Course",
    artistId: "sector-seven",
    albumId: "sector-seven_furnace-transmission",
    trackNumber: 10,
    difficulty: 3,
    energy: 5,
    moodTags: ["driving", "uplifting", "melodic"],
    recommendedWeight: 1,
    availability: "included",
    config: SONG10_CONFIG,
  },
];
