// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const HOT_ROOM_SONG: SongManifest = {
  id: "subterranean_hot-room",
  slug: "hot-room",
  title: "Hot Room",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 4,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropPreset: 'radar-shrine',
  backdropParams: {
    variant: 'ghost-orchid',
  },
  loadConfig: async () => (await import("./config")).SONG4_CONFIG,
};
