// Generated by scripts/scaffold_content.py
import type { ArtistManifest } from "../../schema";

export const SUBTERRANEAN_ARTIST: ArtistManifest = {
  id: "subterranean",
  slug: "subterranean",
  name: "Subterranean",
};
