// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const THAT_UNIT_SONG: SongManifest = {
  id: "subterranean_that-unit",
  slug: "that-unit",
  title: "That Unit",
  artistId: "subterranean",
  albumId: "subterranean_gracie-s-oasis",
  trackNumber: 10,
  difficulty: 5,
  energy: 3,
  moodTags: [
    "melodic",
    "uplifting",
    "deep house",
    "ambient house",
    "microhouse"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'peach',
  },
  loadConfig: async () => (await import("./config")).SONG10_CONFIG,
};
