// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";
import { SONG13_CONFIG } from "./config";

export const WOODEN_SNARES_SONG: SongManifest = {
  id: "subterranean_wooden-snares",
  slug: "wooden-snares",
  title: "Wooden Snares",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 13,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "hidden",
  config: SONG13_CONFIG,
};
