// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";
import { SONG5_CONFIG } from "./config";

export const ANALGESIC_SONG: SongManifest = {
  id: "subterranean_analgesic",
  slug: "analgesic",
  title: "Analgesic",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 5,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  config: SONG5_CONFIG,
};
