// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";
import { SONG7_CONFIG } from "./config";

export const JUMP_JUMPER_SONG: SongManifest = {
  id: "subterranean_jump-jumper",
  slug: "jump-jumper",
  title: "Jump Jumper",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 7,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "hidden",
  config: SONG7_CONFIG,
};
