// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const JUMP_JUMPER_SONG: SongManifest = {
  id: "subterranean_jump-jumper",
  slug: "jump-jumper",
  title: "Jump Jumper",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 7,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropPreset: 'radar-shrine',
  backdropParams: {
    variant: 'aurora',
  },
  loadConfig: async () => (await import("./config")).SONG7_CONFIG,
};
