#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import soundfile as sf
from scipy.signal import get_window, stft


ROOT_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
MODES = {
    "ionian": [0, 2, 4, 5, 7, 9, 11],
    "aeolian": [0, 2, 3, 5, 7, 8, 10],
    "dorian": [0, 2, 3, 5, 7, 9, 10],
    "phrygian": [0, 1, 3, 5, 7, 8, 10],
    "lydian": [0, 2, 4, 6, 7, 9, 11],
    "locrian": [0, 1, 3, 5, 6, 8, 10],
    "mixolydian": [0, 2, 4, 5, 7, 9, 10],
    "harmonicMinor": [0, 2, 3, 5, 7, 8, 11],
    "melodicMinor": [0, 2, 3, 5, 7, 9, 11],
    "bluesMajor": [0, 2, 3, 4, 7, 9],
    "bluesMinor": [0, 3, 5, 6, 7, 10],
    "pentatonicMajor": [0, 2, 4, 7, 9],
    "pentatonicMinor": [0, 3, 5, 7, 10],
}


@dataclass
class Transport:
    bpm: float
    beats_per_bar: int


@dataclass
class SongIdentity:
    key: str
    slug: str


@dataclass
class Suggestion:
    root: str
    mode: str
    score: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze song clips and suggest likely roots/modes by bar.",
    )
    parser.add_argument(
        "targets",
        nargs="*",
        default=["src/content/albums"],
        help="Song folders, album folders, or content roots to scan. Defaults to ./src/content/albums",
    )
    parser.add_argument(
        "--output",
        default="docs/harmony_suggestions.md",
        help="Markdown report path",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=3,
        help="How many suggestions to keep per segment",
    )
    parser.add_argument(
        "--bpm",
        type=float,
        help="Fallback BPM when no matching song config is found",
    )
    parser.add_argument(
        "--beats-per-bar",
        type=int,
        default=4,
        help="Fallback beats per bar when no matching song config is found",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    content_root = repo_root / "src" / "content" / "albums"
    targets = resolve_targets(repo_root, content_root, args.targets)

    report_lines = [
        "# Harmony Suggestions",
        "",
        "Generated by `scripts/analyze_harmony.py`.",
        "",
        "Scoring is chroma/template-based, so treat this as a starting point rather than ground truth.",
        "",
    ]

    report_json: dict[str, object] = {"songs": {}}

    for target in targets:
        transport = resolve_transport(target, args.bpm, args.beats_per_bar)
        song_identity = resolve_song_identity(target)
        song_name = song_identity.slug
        report_lines.extend(
            [
                f"## {song_name}",
                "",
                f"- BPM: `{transport.bpm:g}`",
                f"- Beats per bar: `{transport.beats_per_bar}`",
                "",
            ]
        )

        song_results = []
        for clip_path in sorted(target.glob("*.ogg")):
            result = analyze_clip(clip_path, transport, args.top)
            song_results.append(result)
            report_lines.extend(format_clip_markdown(clip_path.name, result))

        report_json["songs"][song_identity.key] = {
            "transport": {"bpm": transport.bpm, "beatsPerBar": transport.beats_per_bar},
            "clips": song_results,
        }

    output_path = repo_root / args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(report_lines), encoding="utf-8")

    json_path = output_path.with_suffix(".json")
    json_payload = json.dumps(report_json, indent=2)
    json_path.write_text(json_payload, encoding="utf-8")

    public_json_path = repo_root / "public" / "docs" / "harmony_suggestions.json"
    public_json_path.parent.mkdir(parents=True, exist_ok=True)
    public_json_path.write_text(json_payload, encoding="utf-8")

    print(f"Wrote {output_path.relative_to(repo_root)}")
    print(f"Wrote {json_path.relative_to(repo_root)}")
    print(f"Wrote {public_json_path.relative_to(repo_root)}")


def resolve_targets(repo_root: Path, content_root: Path, raw_targets: Iterable[str]) -> list[Path]:
    resolved: list[Path] = []
    for raw_target in raw_targets:
        path = (repo_root / raw_target).resolve()
        if path == content_root.resolve():
            resolved.extend(sorted(p for p in content_root.glob("*/songs/*/audio") if p.is_dir()))
            continue
        if path.is_dir():
            if any(path.glob("*.ogg")):
                resolved.append(path)
                continue
            resolved.extend(sorted(p for p in path.glob("songs/*/audio") if p.is_dir()))
    return resolved


def resolve_transport(
    song_dir: Path,
    fallback_bpm: float | None,
    fallback_beats_per_bar: int,
) -> Transport:
    config_path = song_dir.parent / "config.ts"
    if config_path.exists():
        text = config_path.read_text(encoding="utf-8")
        bpm_match = re.search(r"bpm:\s*([0-9]+(?:\.[0-9]+)?)", text)
        beats_match = re.search(r"beatsPerBar:\s*([0-9]+)", text)
        if bpm_match and beats_match:
            return Transport(float(bpm_match.group(1)), int(beats_match.group(1)))

    return Transport(fallback_bpm or 120.0, fallback_beats_per_bar)


def resolve_song_identity(song_dir: Path) -> SongIdentity:
    song_dir_name = song_dir.parent.name
    song_manifest_path = song_dir.parent / "song.ts"
    if song_manifest_path.exists():
        text = song_manifest_path.read_text(encoding="utf-8")
        id_match = re.search(r'id:\s*"([^"]+)"', text)
        slug_match = re.search(r'slug:\s*"([^"]+)"', text)
        if id_match:
            return SongIdentity(
                key=id_match.group(1),
                slug=slug_match.group(1) if slug_match else song_dir_name,
            )

    return SongIdentity(key=song_dir_name, slug=song_dir_name)


def analyze_clip(path: Path, transport: Transport, top_n: int) -> dict[str, object]:
    signal, sample_rate = load_mono(path)
    chroma, frame_times = compute_chroma(signal, sample_rate)
    overall = summarize_chroma(chroma, top_n)

    bar_seconds = 60.0 / transport.bpm * transport.beats_per_bar
    duration = len(signal) / sample_rate
    estimated_bars = max(1, int(round(duration / bar_seconds)))

    bar_suggestions = []
    for bar_index in range(estimated_bars):
        start = bar_index * bar_seconds
        end = min(duration, (bar_index + 1) * bar_seconds)
        start_frame = int(np.searchsorted(frame_times, start, side="left"))
        end_frame = max(start_frame + 1, int(np.searchsorted(frame_times, end, side="left")))
        bar_chroma = chroma[:, start_frame:end_frame]
        bar_suggestions.append(
            {
                "bar": bar_index + 1,
                "startSeconds": round(start, 3),
                "endSeconds": round(end, 3),
                "suggestions": [suggestion.__dict__ for suggestion in summarize_chroma(bar_chroma, top_n)],
            }
        )

    return {
        "file": path.name,
        "durationSeconds": round(duration, 3),
        "estimatedBars": estimated_bars,
        "overall": [suggestion.__dict__ for suggestion in overall],
        "bars": bar_suggestions,
    }


def load_mono(path: Path) -> tuple[np.ndarray, int]:
    signal, sample_rate = sf.read(path)
    if signal.ndim > 1:
      signal = np.mean(signal, axis=1)
    signal = signal.astype(np.float32, copy=False)
    peak = float(np.max(np.abs(signal))) if signal.size else 0.0
    if peak > 0:
        signal = signal / peak
    return signal, int(sample_rate)


def compute_chroma(signal: np.ndarray, sample_rate: int) -> tuple[np.ndarray, np.ndarray]:
    n_fft = 4096
    hop_length = 1024
    window = get_window("hann", n_fft, fftbins=True)
    freqs, times, spectrum = stft(
        signal,
        fs=sample_rate,
        window=window,
        nperseg=n_fft,
        noverlap=n_fft - hop_length,
        boundary=None,
        padded=False,
    )
    magnitude = np.abs(spectrum)
    chroma = np.zeros((12, magnitude.shape[1]), dtype=np.float64)

    for freq_index, freq in enumerate(freqs):
        if freq < 27.5 or freq > 5000:
            continue
        midi = 69 + 12 * np.log2(freq / 440.0)
        pitch_class = int(round(midi)) % 12
        weight = magnitude[freq_index]
        chroma[pitch_class] += weight

    norms = np.sum(chroma, axis=0)
    nonzero = norms > 1e-9
    chroma[:, nonzero] /= norms[nonzero]
    return chroma, times


def summarize_chroma(chroma: np.ndarray, top_n: int) -> list[Suggestion]:
    energy = np.mean(np.maximum(chroma, 0), axis=1)
    if float(np.sum(energy)) <= 1e-9:
        return [Suggestion("C", "ionian", 0.0)]

    profile = energy / np.sum(energy)
    suggestions: list[Suggestion] = []
    for root_index, root_name in enumerate(ROOT_NAMES):
        for mode_name, intervals in MODES.items():
            mask = np.zeros(12, dtype=float)
            for interval in intervals:
                mask[(root_index + interval) % 12] = 1.0
            mask /= np.sum(mask)

            in_scale = float(np.sum(profile * mask))
            emphasis = float(np.sum(profile * np.roll(mask, 0)))
            root_weight = float(profile[root_index])
            score = in_scale * 0.82 + root_weight * 0.12 + emphasis * 0.06
            suggestions.append(Suggestion(root_name, mode_name, round(score, 4)))

    suggestions.sort(key=lambda item: item.score, reverse=True)
    return suggestions[:top_n]


def format_clip_markdown(file_name: str, result: dict[str, object]) -> list[str]:
    overall = result["overall"]
    bars = result["bars"]
    lines = [
        f"### {file_name}",
        "",
        f"- Duration: `{result['durationSeconds']}s`",
        f"- Estimated bars: `{result['estimatedBars']}`",
        f"- Overall: `{format_suggestions(overall)}`",
        "",
        "| Bar | Suggestion 1 | Suggestion 2 | Suggestion 3 |",
        "| --- | --- | --- | --- |",
    ]

    for bar in bars:
        suggestions = bar["suggestions"]
        padded = list(suggestions) + [{"root": "-", "mode": "-", "score": 0.0}] * max(0, 3 - len(suggestions))
        lines.append(
            f"| {bar['bar']} | {format_cell(padded[0])} | {format_cell(padded[1])} | {format_cell(padded[2])} |"
        )

    lines.append("")
    return lines


def format_suggestions(suggestions: list[dict[str, object]] | list[Suggestion]) -> str:
    parts = []
    for suggestion in suggestions:
        if isinstance(suggestion, Suggestion):
            parts.append(f"{suggestion.root} {suggestion.mode} ({suggestion.score:.3f})")
        else:
            parts.append(f"{suggestion['root']} {suggestion['mode']} ({float(suggestion['score']):.3f})")
    return ", ".join(parts)


def format_cell(suggestion: dict[str, object]) -> str:
    return f"`{suggestion['root']} {suggestion['mode']}` `{float(suggestion['score']):.3f}`"


if __name__ == "__main__":
    main()
