#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


GENERATED_HEADER = "// Generated by scripts/scaffold_content.py\n"


@dataclass
class AlbumContext:
    album_dir: Path
    album_id: str
    artist_id: str
    song_ids: list[str]
    recommended_song_id: str | None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scaffold album and song packages for content authoring.")
    parser.add_argument(
        "--content-root",
        default="src/content",
        help="Content root. Defaults to src/content",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned changes without writing files",
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    album_parser = subparsers.add_parser("album", help="Create a new album package")
    album_parser.add_argument(
        "--dry-run",
        action="store_true",
        default=argparse.SUPPRESS,
        help="Print planned changes without writing files",
    )
    album_parser.add_argument("--artist-id", required=True, help="Artist id, e.g. sector-seven")
    album_parser.add_argument("--artist-name", help="Artist display name; required if the artist does not exist")
    album_parser.add_argument("--album-id", help="Album id; defaults from title")
    album_parser.add_argument("--title", required=True, help="Album title")
    album_parser.add_argument("--year", type=int, help="Album year")
    album_parser.add_argument("--description", default="", help="Album description")
    album_parser.add_argument("--sort-order", type=int, default=999, help="Album sort order")
    album_parser.add_argument(
        "--availability",
        default="hidden",
        choices=["included", "locked", "hidden"],
        help="Initial album availability. Defaults to hidden",
    )
    album_parser.add_argument(
        "--tags",
        default="",
        help="Comma-separated album tags",
    )
    album_parser.add_argument("--accent", default="#7ee9ef")
    album_parser.add_argument("--accent-soft", default="#213645")
    album_parser.add_argument("--text", default="#eaf7ff")
    album_parser.add_argument("--background", default="#081522")
    album_parser.add_argument("--panel", default="#101b29")
    album_parser.add_argument("--backdrop-preset", default="sheffield-club")
    album_parser.add_argument(
        "--backdrop-param",
        action="append",
        default=[],
        help="Backdrop param as key=value. Can be passed multiple times.",
    )

    song_parser = subparsers.add_parser("song", help="Create a new song package within an album")
    song_parser.add_argument(
        "--dry-run",
        action="store_true",
        default=argparse.SUPPRESS,
        help="Print planned changes without writing files",
    )
    song_parser.add_argument("--album-id", required=True, help="Parent album id")
    song_parser.add_argument("--title", required=True, help="Song title")
    song_parser.add_argument("--song-slug", help="Song folder slug; defaults from title")
    song_parser.add_argument("--song-id", help="Song id; defaults to <artist-id>_<song-slug>")
    song_parser.add_argument("--track-number", type=int, required=True, help="Track number in album")
    song_parser.add_argument("--difficulty", type=int, default=3, choices=[1, 2, 3, 4, 5])
    song_parser.add_argument("--energy", type=int, default=3, choices=[1, 2, 3, 4, 5])
    song_parser.add_argument("--recommended-weight", type=float, default=0.7)
    song_parser.add_argument(
        "--availability",
        default="hidden",
        choices=["included", "locked", "hidden"],
        help="Initial song availability. Defaults to hidden",
    )
    song_parser.add_argument(
        "--mood-tags",
        default="dark,driving",
        help="Comma-separated mood tags",
    )
    song_parser.add_argument("--root-note", default="C")
    song_parser.add_argument("--mode", default="pentatonicMinor")
    song_parser.add_argument("--bpm", type=int, default=120)
    song_parser.add_argument("--beats-per-bar", type=int, default=4)
    song_parser.add_argument("--bars-per-loop", type=int, default=4)
    song_parser.add_argument("--harmony-cycle-bars", type=int, default=8)
    song_parser.add_argument("--intro-bars", type=int, default=2)
    song_parser.add_argument("--main-bars", type=int, default=4)
    song_parser.add_argument(
        "--placeholder-prefix",
        default="01",
        help='Prefix for placeholder loop files, e.g. "01" creates 01i.ogg / 01m.ogg',
    )

    return parser.parse_args()


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "untitled"


def const_name(slug: str, suffix: str) -> str:
    tokens = re.split(r"[^a-zA-Z0-9]+", slug)
    return "_".join(token.upper() for token in tokens if token) + suffix


def indent(text: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line else "" for line in text.splitlines())


def format_string_array(values: Iterable[str], spaces: int = 4) -> str:
    values = list(values)
    if not values:
        return "[]"
    body = ",\n".join((" " * spaces) + f'"{value}"' for value in values)
    return "[\n" + body + "\n]"


def parse_backdrop_params(values: list[str]) -> dict[str, str | int | float | bool]:
    params: dict[str, str | int | float | bool] = {}
    for raw in values:
        if "=" not in raw:
            raise SystemExit(f"Invalid --backdrop-param '{raw}'. Expected key=value.")
        key, raw_value = raw.split("=", 1)
        value: str | int | float | bool
        normalized = raw_value.strip()
        if normalized.lower() in {"true", "false"}:
            value = normalized.lower() == "true"
        else:
            try:
                value = int(normalized)
            except ValueError:
                try:
                    value = float(normalized)
                except ValueError:
                    value = normalized
        params[key.strip()] = value
    return params


def render_backdrop_params(params: dict[str, str | int | float | bool]) -> str:
    if not params:
        return ""
    lines = []
    for key, value in params.items():
        if isinstance(value, str):
            rendered = f'"{value}"'
        elif isinstance(value, bool):
            rendered = "true" if value else "false"
        else:
            rendered = str(value)
        lines.append(f"      {key}: {rendered},")
    return "    backdropParams: {\n" + "\n".join(lines) + "\n    },\n"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_file(path: Path, text: str, dry_run: bool) -> None:
    if dry_run:
        print(f"[dry-run] write {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def touch_file(path: Path, dry_run: bool) -> None:
    if dry_run:
        print(f"[dry-run] touch {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.touch(exist_ok=True)


def ensure_dir(path: Path, dry_run: bool) -> None:
    if dry_run:
        print(f"[dry-run] mkdir -p {path}")
        return
    path.mkdir(parents=True, exist_ok=True)


def load_album_context(content_root: Path, album_id: str) -> AlbumContext:
    album_dir = content_root / "albums" / album_id
    album_file = album_dir / "album.ts"
    if not album_file.exists():
        raise SystemExit(f"Album manifest not found: {album_file}")

    album_text = read_text(album_file)
    artist_match = re.search(r'artistId:\s*"([^"]+)"', album_text)
    song_ids_match = re.search(r"songIds:\s*\[(?P<body>.*?)\]", album_text, flags=re.S)
    recommended_match = re.search(r'recommendedSongId:\s*"([^"]+)"', album_text)
    if not artist_match or song_ids_match is None:
        raise SystemExit(f"Could not parse album manifest: {album_file}")

    song_ids = re.findall(r'"([^"]+)"', song_ids_match.group("body"))
    return AlbumContext(
      album_dir=album_dir,
      album_id=album_id,
      artist_id=artist_match.group(1),
      song_ids=song_ids,
      recommended_song_id=recommended_match.group(1) if recommended_match else None,
    )


def update_album_song_ids(album_ctx: AlbumContext, song_id: str, dry_run: bool) -> None:
    album_file = album_ctx.album_dir / "album.ts"
    text = read_text(album_file)
    next_song_ids = album_ctx.song_ids + ([] if song_id in album_ctx.song_ids else [song_id])
    rendered = ",\n".join(f'    "{value}"' for value in next_song_ids)
    text = re.sub(r"songIds:\s*\[(?P<body>.*?)\],", f"songIds: [\n{rendered}\n  ],", text, flags=re.S)
    if not album_ctx.recommended_song_id:
        text = re.sub(r"recommendedSongId:\s*[^,\n]+,?", f'recommendedSongId: "{song_id}",', text)
    write_file(album_file, text, dry_run)


def sync_artists_index(content_root: Path, dry_run: bool) -> None:
    artist_root = content_root / "artists"
    artist_files = sorted(artist_root.glob("*/artist.ts"))
    imports: list[str] = []
    exports: list[str] = []
    for artist_file in artist_files:
        text = read_text(artist_file)
        match = re.search(r"export const (\w+):", text)
        if not match:
            continue
        const = match.group(1)
        rel = artist_file.parent.name
        imports.append(f'import {{ {const} }} from "./{rel}/artist";')
        exports.append(const)
    body = GENERATED_HEADER
    if imports:
        body += "\n".join(imports) + "\n"
    body += 'import type { ArtistManifest } from "../schema";\n\n'
    body += f"export const ARTISTS: ArtistManifest[] = [{', '.join(exports)}];\n"
    write_file(artist_root / "index.ts", body, dry_run)


def sync_album_songs_index(album_dir: Path, dry_run: bool) -> None:
    songs_root = album_dir / "songs"
    song_entries: list[tuple[int, str, str]] = []
    for song_file in songs_root.glob("*/song.ts"):
        text = read_text(song_file)
        const_match = re.search(r"export const (\w+):", text)
        track_match = re.search(r"trackNumber:\s*(\d+)", text)
        if not const_match or not track_match:
            continue
        song_entries.append((int(track_match.group(1)), const_match.group(1), song_file.parent.name))

    song_entries.sort(key=lambda entry: (entry[0], entry[2]))
    imports: list[str] = []
    exports: list[str] = []
    for _, const, rel in song_entries:
        imports.append(f'import {{ {const} }} from "./{rel}/song";')
        exports.append(const)

    body = GENERATED_HEADER
    if imports:
        body += "\n".join(imports) + "\n"
    body += 'import type { SongManifest } from "../../../schema";\n\n'
    album_const = const_name(album_dir.name, "_SONGS")
    body += f"export const {album_const}: SongManifest[] = [\n"
    for const in exports:
        body += f"  {const},\n"
    body += "];\n"
    write_file(songs_root / "index.ts", body, dry_run)


def sync_albums_index(content_root: Path, dry_run: bool) -> None:
    albums_root = content_root / "albums"
    album_entries: list[tuple[int, str, str, str]] = []
    imports: list[str] = []
    song_exports: list[str] = []
    for album_file in albums_root.glob("*/album.ts"):
        text = read_text(album_file)
        album_match = re.search(r"export const (\w+):", text)
        sort_match = re.search(r"sortOrder:\s*(\d+)", text)
        if not album_match:
            continue
        album_const = album_match.group(1)
        rel = album_file.parent.name
        songs_index = album_file.parent / "songs" / "index.ts"
        if not songs_index.exists():
            continue
        songs_text = read_text(songs_index)
        songs_match = re.search(r"export const (\w+):", songs_text)
        if not songs_match:
            continue
        songs_const = songs_match.group(1)
        sort_order = int(sort_match.group(1)) if sort_match else 999
        album_entries.append((sort_order, rel, album_const, songs_const))

    album_entries.sort(key=lambda entry: (entry[0], entry[1]))
    album_exports: list[str] = []
    for _, rel, album_const, songs_const in album_entries:
        imports.append(f'import {{ {album_const} }} from "./{rel}/album";')
        imports.append(f'import {{ {songs_const} }} from "./{rel}/songs";')
        album_exports.append(album_const)
        song_exports.append(f"...{songs_const}")

    body = GENERATED_HEADER
    if imports:
        body += "\n".join(imports) + "\n"
    body += 'import type { AlbumManifest, SongManifest } from "../schema";\n\n'
    body += f"export const ALBUMS: AlbumManifest[] = [{', '.join(album_exports)}];\n\n"
    body += f"export const SONGS: SongManifest[] = [{', '.join(song_exports)}];\n"
    write_file(albums_root / "index.ts", body, dry_run)


def scaffold_artist(content_root: Path, artist_id: str, artist_name: str | None, dry_run: bool) -> None:
    artist_dir = content_root / "artists" / artist_id
    artist_file = artist_dir / "artist.ts"
    if artist_file.exists():
        return
    if not artist_name:
        raise SystemExit(f"Artist '{artist_id}' does not exist. Pass --artist-name to create it.")
    const = const_name(artist_id, "_ARTIST")
    body = GENERATED_HEADER
    body += 'import type { ArtistManifest } from "../../schema";\n\n'
    body += f"export const {const}: ArtistManifest = {{\n"
    body += f'  id: "{artist_id}",\n'
    body += f'  slug: "{artist_id}",\n'
    body += f'  name: "{artist_name}",\n'
    body += "};\n"
    write_file(artist_file, body, dry_run)


def scaffold_album(args: argparse.Namespace, content_root: Path) -> None:
    album_id = args.album_id or f'{args.artist_id}_{slugify(args.title)}'
    album_dir = content_root / "albums" / album_id
    album_file = album_dir / "album.ts"
    if album_file.exists():
        raise SystemExit(f"Album already exists: {album_id}")

    scaffold_artist(content_root, args.artist_id, args.artist_name, args.dry_run)
    ensure_dir(album_dir / "songs", args.dry_run)
    backdrop_params = parse_backdrop_params(args.backdrop_param)
    const = const_name(album_id, "_ALBUM")
    tags = [tag.strip() for tag in args.tags.split(",") if tag.strip()]
    body = GENERATED_HEADER
    body += 'import type { AlbumManifest } from "../../schema";\n\n'
    body += f"export const {const}: AlbumManifest = {{\n"
    body += f'  id: "{album_id}",\n'
    body += f'  slug: "{album_id}",\n'
    body += f'  title: "{args.title}",\n'
    body += f'  artistId: "{args.artist_id}",\n'
    if args.year:
        body += f"  year: {args.year},\n"
    if args.description:
        body += f'  description: "{args.description}",\n'
    body += "  theme: {\n"
    body += f'    accent: "{args.accent}",\n'
    body += f'    accentSoft: "{args.accent_soft}",\n'
    body += f'    text: "{args.text}",\n'
    body += f'    background: "{args.background}",\n'
    body += f'    panel: "{args.panel}",\n'
    body += f'    backdropPreset: "{args.backdrop_preset}",\n'
    body += render_backdrop_params(backdrop_params)
    body += "  },\n"
    body += f"  tags: {format_string_array(tags, 4)},\n"
    body += "  songIds: [],\n"
    body += f"  sortOrder: {args.sort_order},\n"
    body += f'  availability: "{args.availability}",\n'
    body += "};\n"
    write_file(album_file, body, args.dry_run)
    sync_artists_index(content_root, args.dry_run)
    sync_album_songs_index(album_dir, args.dry_run)
    sync_albums_index(content_root, args.dry_run)


def scaffold_song(args: argparse.Namespace, content_root: Path) -> None:
    album_ctx = load_album_context(content_root, args.album_id)
    song_slug = args.song_slug or slugify(args.title)
    song_id = args.song_id or f"{album_ctx.artist_id}_{song_slug}"
    song_dir = album_ctx.album_dir / "songs" / song_slug
    if song_dir.exists():
        raise SystemExit(f"Song folder already exists: {song_dir}")

    ensure_dir(song_dir / "audio", args.dry_run)
    placeholder_intro = f"{args.placeholder_prefix}i.ogg"
    placeholder_main = f"{args.placeholder_prefix}m.ogg"
    touch_file(song_dir / "audio" / placeholder_intro, args.dry_run)
    touch_file(song_dir / "audio" / placeholder_main, args.dry_run)

    config_const = f"SONG{args.track_number}_CONFIG"
    config_body = GENERATED_HEADER
    config_body += 'import type { SongConfig } from "../../../../../game/songConfig";\n\n'
    config_body += "const assetUrl = (relativePath: string): string =>\n"
    config_body += '  new URL(`./audio/${relativePath}`, import.meta.url).href;\n\n'
    config_body += f"export const {config_const}: SongConfig = {{\n"
    config_body += f'  id: "song{args.track_number}",\n'
    config_body += "  transport: {\n"
    config_body += f"    bpm: {args.bpm},\n"
    config_body += f"    beatsPerBar: {args.beats_per_bar},\n"
    config_body += f"    barsPerLoop: {args.bars_per_loop},\n"
    config_body += f"    harmonyCycleBars: {args.harmony_cycle_bars},\n"
    config_body += "  },\n"
    config_body += "  harmonyTimeline: [\n"
    config_body += (
      f'    {{ startBar: 1, lengthBars: {args.harmony_cycle_bars}, rootNote: "{args.root_note}", mode: "{args.mode}" }},\n'
    )
    config_body += "  ],\n"
    config_body += "  grooveLevels: [\n"
    config_body += "    {\n"
    config_body += "      level: 1,\n"
    config_body += "      main: {\n"
    config_body += f'        src: assetUrl("{placeholder_main}"),\n'
    config_body += f"        bars: {args.main_bars},\n"
    config_body += "      },\n"
    config_body += "      intro: {\n"
    config_body += f'        src: assetUrl("{placeholder_intro}"),\n'
    config_body += f"        bars: {args.intro_bars},\n"
    config_body += "      },\n"
    config_body += "    },\n"
    config_body += "  ],\n"
    config_body += "};\n"
    write_file(song_dir / "config.ts", config_body, args.dry_run)

    mood_tags = [tag.strip() for tag in args.mood_tags.split(",") if tag.strip()]
    manifest_const = const_name(song_slug, "_SONG")
    song_body = GENERATED_HEADER
    song_body += 'import type { SongManifest } from "../../../../schema";\n'
    song_body += f'import {{ {config_const} }} from "./config";\n\n'
    song_body += f"export const {manifest_const}: SongManifest = {{\n"
    song_body += f'  id: "{song_id}",\n'
    song_body += f'  slug: "{song_slug}",\n'
    song_body += f'  title: "{args.title}",\n'
    song_body += f'  artistId: "{album_ctx.artist_id}",\n'
    song_body += f'  albumId: "{album_ctx.album_id}",\n'
    song_body += f"  trackNumber: {args.track_number},\n"
    song_body += f"  difficulty: {args.difficulty},\n"
    song_body += f"  energy: {args.energy},\n"
    song_body += f"  moodTags: {format_string_array(mood_tags, 4)},\n"
    song_body += f"  recommendedWeight: {args.recommended_weight},\n"
    song_body += f'  availability: "{args.availability}",\n'
    song_body += f"  config: {config_const},\n"
    song_body += "};\n"
    write_file(song_dir / "song.ts", song_body, args.dry_run)

    update_album_song_ids(album_ctx, song_id, args.dry_run)
    sync_album_songs_index(album_ctx.album_dir, args.dry_run)
    sync_albums_index(content_root, args.dry_run)

    if args.dry_run:
        print(
            "[dry-run] note: scaffolded songs default to hidden availability and zero-byte placeholder audio files; "
            "replace them before making the song visible."
        )


def main() -> None:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    content_root = (repo_root / args.content_root).resolve()

    if args.command == "album":
        scaffold_album(args, content_root)
    elif args.command == "song":
        scaffold_song(args, content_root)
    else:
        raise SystemExit(f"Unknown command: {args.command}")


if __name__ == "__main__":
    main()
