// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const LESS_WEALTH_SONG: SongManifest = {
  id: "chemikal-foods-ltd_less-wealth",
  slug: "less-wealth",
  title: "Less Wealth",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 4,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG4_CONFIG,
};
