// Generated by scripts/scaffold_content.py
import { BRUTALIST_CLUB_BACKDROP_MODULE } from "./presets/brutalist-club";
import { RADAR_SHRINE_BACKDROP } from "./presets/radar-shrine";
import { SCAFFOLD_TEST_BACKDROP } from "./presets/scaffold-test";
import type { BackdropModule } from "./schema";

export const BACKDROP_MODULES: BackdropModule[] = [
  BRUTALIST_CLUB_BACKDROP_MODULE,
  RADAR_SHRINE_BACKDROP,
  SCAFFOLD_TEST_BACKDROP,
];

export const BACKDROP_MODULE_MAP = new Map(
  BACKDROP_MODULES.map((module) => [module.id, module] as const),
);

export const getBackdropModuleById = (backdropId: string): BackdropModule | undefined =>
  BACKDROP_MODULE_MAP.get(backdropId);
