// Generated by scripts/scaffold_content.py
import type { AlbumManifest } from "../../schema";
import sectorSevenArtificialHeatCover from "./cover.png";

export const SECTOR_SEVEN_ARTIFICIAL_HEAT_ALBUM: AlbumManifest = {
  id: "sector-seven_artificial-heat",
  slug: "sector-seven_artificial-heat",
  title: "Artificial Heat",
  artistId: "sector-seven",
  coverArt: sectorSevenArtificialHeatCover,
  year: 2026,
  theme: {
    accent: "#7ee9ef",
    accentSoft: "#213645",
    text: "#eaf7ff",
    background: "#081522",
    panel: "#101b29",
    backdropPreset: "radar-shrine",
  },
  tags: [
    "deep house",
    "ambient house",
    "microhouse"
],
  songIds: [
    "sector-seven_drunk-again",
    "sector-seven_naturally",
    "sector-seven_i-saw-the-sky",
    "sector-seven_distorted-by-fear",
    "sector-seven_twisted",
    "sector-seven_tumbling-down",
    "sector-seven_a-glimpse-of-green",
    "sector-seven_triangles",
    "sector-seven_burning",
    "sector-seven_with-no-sound"
  ],
  sortOrder: 999,
  availability: "included",
};
