// Generated by scripts/scaffold_content.py
import type { SongConfig } from "../../../../../game/songConfig";

const assetUrl = (relativePath: string): string =>
  new URL(`./audio/${relativePath}`, import.meta.url).href;

export const SONG2_CONFIG: SongConfig = {
  id: "song2",
  transport: {
    bpm: 125,
    beatsPerBar: 4,
    barsPerLoop: 4,
    harmonyCycleBars: 8,
  },
  harmonyTimeline: [
    { startBar: 1, lengthBars: 8, rootNote: "C", mode: "pentatonicMinor" },
  ],
  grooveLevels: [
    {
      level: 1,
      main: {
        src: assetUrl("01m.ogg"),
        bars: 4,
      },
      intro: {
        src: assetUrl("01i.ogg"),
        bars: 2,
      },
    },
    {
      level: 2,
      main: {
        src: assetUrl("02m.ogg"),
        bars: 4,
      },
      intro: {
        src: assetUrl("02i.ogg"),
        bars: 4,
      },
    },
    {
      level: 3,
      main: {
        src: assetUrl("03m.ogg"),
        bars: 4,
      },
      intro: {
        src: assetUrl("03i.ogg"),
        bars: 4,
      },
    },
    {
      level: 4,
      main: {
        src: assetUrl("04m.ogg"),
        bars: 4,
      },
      intro: {
        src: assetUrl("04i.ogg"),
        bars: 4,
      },
    },
    {
      level: 5,
      main: {
        src: assetUrl("05m.ogg"),
        bars: 4,
      },
      intro: {
        src: assetUrl("05i.ogg"),
        bars: 4,
      },
    },
    {
      level: 6,
      main: {
        src: assetUrl("06m.ogg"),
        bars: 4,
      },
      intro: {
        src: assetUrl("06i.ogg"),
        bars: 4,
      },
    },
    {
      level: 7,
      main: {
        src: assetUrl("07m.ogg"),
        bars: 4,
      },
      intro: {
        src: assetUrl("07i.ogg"),
        bars: 4,
      },
    },
    {
      level: 8,
      main: {
        src: assetUrl("08m.ogg"),
        bars: 4,
      },
      intro: {
        src: assetUrl("08i.ogg"),
        bars: 4,
      },
    },
    {
      level: 9,
      main: {
        src: assetUrl("09m.ogg"),
        bars: 4,
      },
      intro: {
        src: assetUrl("09i.ogg"),
        bars: 4,
      },
    },
    {
      level: 10,
      intro: {
        src: assetUrl("10i.ogg"),
        bars: 4,
      },
      completesSong: true,
    },
  ],
};
