// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";
import { SONG2_CONFIG } from "./config";

export const SHOVEL_SONG: SongManifest = {
  id: "subterranean_shovel",
  slug: "shovel",
  title: "Shovel",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 2,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "hidden",
  config: SONG2_CONFIG,
};
