// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const SHOVEL_SONG: SongManifest = {
  id: "subterranean_shovel",
  slug: "shovel",
  title: "Shovel",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 2,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropPreset: 'radar-shrine',
  backdropParams: {
    variant: 'aurora',
  },
  loadConfig: async () => (await import("./config")).SONG2_CONFIG,
};
