// Generated by scripts/scaffold_content.py
import { LOST_IT_ON_SCHAEFER_SONG } from "./lost-it-on-schaefer/song";
import { CHASING_SONG } from "./chasing/song";
import { GOT_IT_LOCKED_SONG } from "./got-it-locked/song";
import { THE_PLATE_SONG } from "./the-plate/song";
import { NORTHBOUND_SONG } from "./northbound/song";
import { STITCHES_SONG } from "./stitches/song";
import { FROM_THE_LODGE_SONG } from "./from-the-lodge/song";
import { THE_BENCH_SONG } from "./the-bench/song";
import { WRIST_AND_PALM_SONG } from "./wrist-and-palm/song";
import { THAT_UNIT_SONG } from "./that-unit/song";
import { GRACIE_S_OASIS_SONG } from "./gracie-s-oasis/song";
import type { SongManifest } from "../../../schema";

export const SUBTERRANEAN_GRACIE_S_OASIS_SONGS: SongManifest[] = [
  LOST_IT_ON_SCHAEFER_SONG,
  CHASING_SONG,
  GOT_IT_LOCKED_SONG,
  THE_PLATE_SONG,
  NORTHBOUND_SONG,
  STITCHES_SONG,
  FROM_THE_LODGE_SONG,
  THE_BENCH_SONG,
  WRIST_AND_PALM_SONG,
  THAT_UNIT_SONG,
  GRACIE_S_OASIS_SONG,
];
