// Generated by scripts/scaffold_content.py
import type { AlbumManifest } from "../../schema";
import chemikalFoodsLtdCover from "./cover.webp";

export const CHEMIKAL_FOODS_LTD_MANIFESTATION_ALBUM: AlbumManifest = {
  id: "chemikal-foods-ltd_manifestation",
  slug: "chemikal-foods-ltd_manifestation",
  title: "Manifestation",
  artistId: "chemikal-foods-ltd",
  coverArt: chemikalFoodsLtdCover,
  year: 2026,
  theme: {
    accent: "#7ee9ef",
    accentSoft: "#213645",
    text: "#eaf7ff",
    background: "#081522",
    panel: "#101b29",
    backdropPreset: "brutalist-club",
  },
  tags: [
    "Trip Hop",
    "Downtempo",
    "Nu Jazz",
    "Trip Hop",
    "Breakbeat",
    "nocturnal"
],
  songIds: [
    "chemikal-foods-ltd_manifestation",
    "chemikal-foods-ltd_twenty-titles",
    "chemikal-foods-ltd_more-money",
    "chemikal-foods-ltd_less-wealth",
    "chemikal-foods-ltd_trained-to-commit",
    "chemikal-foods-ltd_healthbelt-5",
    "chemikal-foods-ltd_hypno-s-headphones",
    "chemikal-foods-ltd_manatee",
    "chemikal-foods-ltd_a-bridge-with-no-hole",
    "chemikal-foods-ltd_over-the-cliff"
  ],
  sortOrder: 999,
  availability: "included",
};
