// Generated by scripts/scaffold_content.py
import { GIANT_RESET_SONG } from "./giant-reset/song";
import { FATMAN_SONG } from "./fatman/song";
import { SUNUP_SONG } from "./sunup/song";
import { EURO_PACMENZ_SONG } from "./euro-pacmenz/song";
import { CONSTANT_ENOPLE_SONG } from "./constant-enople/song";
import { PABLO_SONG } from "./pablo/song";
import { JELLING_BAD_WORDS_SONG } from "./jelling-bad-words/song";
import { HAMTRACK_SONG } from "./hamtrack/song";
import { BURRIED_SONG } from "./burried/song";
import { RUNNING_ITS_COURSE_SONG } from "./running-its-course/song";
import type { SongManifest } from "../../../schema";

export const SECTOR_SEVEN_FURNACE_TRANSMISSION_SONGS: SongManifest[] = [
  GIANT_RESET_SONG,
  FATMAN_SONG,
  SUNUP_SONG,
  EURO_PACMENZ_SONG,
  CONSTANT_ENOPLE_SONG,
  PABLO_SONG,
  JELLING_BAD_WORDS_SONG,
  HAMTRACK_SONG,
  BURRIED_SONG,
  RUNNING_ITS_COURSE_SONG,
];
