// Generated by scripts/scaffold_content.py
import type { AlbumManifest } from "../../schema";
import subterraneanEchoChamgerCover from "./cover.webp";

export const SUBTERRANEAN_ECHO_CHAMBER_ALBUM: AlbumManifest = {
  id: "subterranean_echo-chamber",
  slug: "subterranean_echo-chamber",
  title: "Echo Chamber",
  artistId: "subterranean",
  coverArt: subterraneanEchoChamgerCover,
  year: 2026,
  theme: {
    accent: "#7ee9ef",
    accentSoft: "#213645",
    text: "#eaf7ff",
    background: "#081522",
    panel: "#101b29",
    backdropPreset: "gatecrasher-reactor",
  },
  tags: [
    "deep house",
    "ambient house",
    "microhouse"
],
  songIds: [
    "subterranean_birmingham-central",
    "subterranean_shovel",
    "subterranean_broken-castle",
    "subterranean_hot-room",
    "subterranean_analgesic",
    "subterranean_over-my-shoulder",
    "subterranean_jump-jumper",
    "subterranean_cheeseboard",
    "subterranean_spar-car-park",
    "subterranean_rolling",
    "subterranean_danger-drive",
    "subterranean_escape-pt-1",
    "subterranean_wooden-snares",
    "subterranean_half-painted",
    "subterranean_rosebloom"
  ],
  sortOrder: 999,
  availability: "included",
};
