// Generated by scripts/scaffold_content.py
import type { AlbumManifest } from "../../schema";

export const SUBTERRANEAN_ECHO_CHAMBER_ALBUM: AlbumManifest = {
  id: "subterranean_echo-chamber",
  slug: "subterranean_echo-chamber",
  title: "Echo Chamber",
  artistId: "subterranean",
  year: 2026,
  theme: {
    accent: "#7ee9ef",
    accentSoft: "#213645",
    text: "#eaf7ff",
    background: "#081522",
    panel: "#101b29",
    backdropPreset: "sheffield-club",
  },
  tags: [
    "deep house",
    "ambient house",
    "microhouse"
],
  songIds: [
    "subterranean_birmingham-central"
  ],
  sortOrder: 999,
  availability: "included",
};
