// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const I_SAW_THE_SKY_SONG: SongManifest = {
  id: "sector-seven_i-saw-the-sky",
  slug: "i-saw-the-sky",
  title: "I Saw the Sky",
  artistId: "sector-seven",
  albumId: "sector-seven_artificial-heat",
  trackNumber: 3,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG3_CONFIG,
};
