// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const HYPNO_S_HEADPHONES_SONG: SongManifest = {
  id: "chemikal-foods-ltd_hypno-s-headphones",
  slug: "hypno-s-headphones",
  title: "Hypno's Headphones",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 7,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG7_CONFIG,
};
