// Generated by scripts/scaffold_content.py
import { CHEMIKAL_FOODS_LTD_ARTIST } from "./chemikal-foods-ltd/artist";
import { SECTOR_SEVEN_ARTIST } from "./sector-seven/artist";
import { SUBTERRANEAN_ARTIST } from "./subterranean/artist";
import type { ArtistManifest } from "../schema";

export const ARTISTS: ArtistManifest[] = [CHEMIKAL_FOODS_LTD_ARTIST, SECTOR_SEVEN_ARTIST, SUBTERRANEAN_ARTIST];
