// Generated by scripts/scaffold_content.py
import { SECTOR_SEVEN_ARTIST } from "./sector-seven/artist";
import { SUBTERRANEAN_ARTIST } from "./subterranean/artist";
import type { ArtistManifest } from "../schema";

export const ARTISTS: ArtistManifest[] = [SECTOR_SEVEN_ARTIST, SUBTERRANEAN_ARTIST];
