// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const SPAR_CAR_PARK_SONG: SongManifest = {
  id: "subterranean_spar-car-park",
  slug: "spar-car-park",
  title: "Spar Car Park",
  artistId: "subterranean",
  albumId: "subterranean_echo-chamber",
  trackNumber: 9,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG9_CONFIG,
};
