// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";
import panorama from "../../assets/brutalist1.webp";

export const MANATEE_SONG: SongManifest = {
  id: "chemikal-foods-ltd_manatee",
  slug: "manatee",
  title: "Manatee",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 8,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  backdropParams: {
    variant: 'dream',
    yawCenterDegrees: 0,
    panoramaUrl: panorama,
    zoom: 0.8,
  },
  loadConfig: async () => (await import("./config")).SONG8_CONFIG,
};
