// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const MANATEE_SONG: SongManifest = {
  id: "chemikal-foods-ltd_manatee",
  slug: "manatee",
  title: "Manatee",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 8,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG8_CONFIG,
};
