// Generated by scripts/scaffold_content.py
import type { SongManifest } from "../../../../schema";

export const TRAINED_TO_COMMIT_SONG: SongManifest = {
  id: "chemikal-foods-ltd_trained-to-commit",
  slug: "trained-to-commit",
  title: "Trained To Commit",
  artistId: "chemikal-foods-ltd",
  albumId: "chemikal-foods-ltd_manifestation",
  trackNumber: 5,
  difficulty: 3,
  energy: 3,
  moodTags: [
    "dark",
    "driving"
],
  recommendedWeight: 0.7,
  availability: "included",
  loadConfig: async () => (await import("./config")).SONG5_CONFIG,
};
