// Generated by scripts/scaffold_content.py
import { SECTOR_SEVEN_FURNACE_TRANSMISSION_ALBUM } from "./sector-seven_furnace-transmission/album";
import { SECTOR_SEVEN_FURNACE_TRANSMISSION_SONGS } from "./sector-seven_furnace-transmission/songs";
import { CHEMIKAL_FOODS_LTD_MANIFESTATION_ALBUM } from "./chemikal-foods-ltd_manifestation/album";
import { CHEMIKAL_FOODS_LTD_MANIFESTATION_SONGS } from "./chemikal-foods-ltd_manifestation/songs";
import { SECTOR_SEVEN_ARTIFICIAL_HEAT_ALBUM } from "./sector-seven_artificial-heat/album";
import { SECTOR_SEVEN_ARTIFICIAL_HEAT_SONGS } from "./sector-seven_artificial-heat/songs";
import { SUBTERRANEAN_ECHO_CHAMBER_ALBUM } from "./subterranean_echo-chamber/album";
import { SUBTERRANEAN_ECHO_CHAMBER_SONGS } from "./subterranean_echo-chamber/songs";
import type { AlbumManifest, SongManifest } from "../schema";

export const ALBUMS: AlbumManifest[] = [SECTOR_SEVEN_FURNACE_TRANSMISSION_ALBUM, CHEMIKAL_FOODS_LTD_MANIFESTATION_ALBUM, SECTOR_SEVEN_ARTIFICIAL_HEAT_ALBUM, SUBTERRANEAN_ECHO_CHAMBER_ALBUM];

export const SONGS: SongManifest[] = [...SECTOR_SEVEN_FURNACE_TRANSMISSION_SONGS, ...CHEMIKAL_FOODS_LTD_MANIFESTATION_SONGS, ...SECTOR_SEVEN_ARTIFICIAL_HEAT_SONGS, ...SUBTERRANEAN_ECHO_CHAMBER_SONGS];
