// Generated by scripts/scaffold_content.py
import { SECTOR_SEVEN_FURNACE_TRANSMISSION_ALBUM } from "./sector-seven_furnace-transmission/album";
import { SECTOR_SEVEN_FURNACE_TRANSMISSION_SONGS } from "./sector-seven_furnace-transmission/songs";
import { SUBTERRANEAN_ECHO_CHAMBER_ALBUM } from "./subterranean_echo-chamber/album";
import { SUBTERRANEAN_ECHO_CHAMBER_SONGS } from "./subterranean_echo-chamber/songs";
import type { AlbumManifest, SongManifest } from "../schema";

export const ALBUMS: AlbumManifest[] = [SECTOR_SEVEN_FURNACE_TRANSMISSION_ALBUM, SUBTERRANEAN_ECHO_CHAMBER_ALBUM];

export const SONGS: SongManifest[] = [...SECTOR_SEVEN_FURNACE_TRANSMISSION_SONGS, ...SUBTERRANEAN_ECHO_CHAMBER_SONGS];
